title: Linkr
description: "Find ideas fast"
owner_name: Men In Brown
github_username: Men-In-Brown
github_repo: "Linkr-Frontend"
baseurl: "/Linkr-Frontend"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/Men-In-Brown"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
